disable health check step as well

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -53,20 +53,20 @@ jobs:
       #     NOTIFY_E2E_TEST_URI: ${{ secrets.NOTIFY_E2E_TEST_URI }}
       - name: Check coverage threshold
         run: poetry run coverage report --fail-under=90
-      - name: Health check
-        run: |
-          response=$(curl -url ${{secrets.NOTIFY_E2E_TEST_URI}}_status)
-          if grep -q "ok" <<< "$response"; then
-            echo "Health check passed"
-          else
-            echo "Health check failed"
-            exit 1
-          fi
-        env:
-          NOTIFY_E2E_AUTH_STATE_PATH: ${{ secrets.NOTIFY_E2E_AUTH_STATE_PATH }}
-          NOTIFY_E2E_TEST_EMAIL: ${{ secrets.NOTIFY_E2E_TEST_EMAIL }}
-          NOTIFY_E2E_TEST_PASSWORD: ${{ secrets.NOTIFY_E2E_TEST_PASSWORD }}
-          NOTIFY_E2E_TEST_URI: ${{ secrets.NOTIFY_E2E_TEST_URI }}
+      # - name: Health check
+      #   run: |
+      #     response=$(curl -url ${{secrets.NOTIFY_E2E_TEST_URI}}_status)
+      #     if grep -q "ok" <<< "$response"; then
+      #       echo "Health check passed"
+      #     else
+      #       echo "Health check failed"
+      #       exit 1
+      #     fi
+      #   env:
+      #     NOTIFY_E2E_AUTH_STATE_PATH: ${{ secrets.NOTIFY_E2E_AUTH_STATE_PATH }}
+      #     NOTIFY_E2E_TEST_EMAIL: ${{ secrets.NOTIFY_E2E_TEST_EMAIL }}
+      #     NOTIFY_E2E_TEST_PASSWORD: ${{ secrets.NOTIFY_E2E_TEST_PASSWORD }}
+      #     NOTIFY_E2E_TEST_URI: ${{ secrets.NOTIFY_E2E_TEST_URI }}
 
   validate-new-relic-config:
     runs-on: ubuntu-latest
